### ISSUE TITLE
Add Digital Ocean Sketch Provider

### ISSUE THREAD

**Issue by willk** [redteaminfra/redteam-infra#72]
Currently linode is the only provider with terraform. TF should be written for other providers.

Example providers with TF support:

- vultr https://registry.terraform.io/providers/vultr/vultr/latest/docs
- ovh: https://registry.terraform.io/providers/ovh/ovh/latest/docs
- digital ocean: https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs

**Comment by devzspy** [comment]
Renaming for just Digital Ocean. I will create other issues for other providers (vultr, ovh, cloudflare, etc)
